name: Publish to JSR

on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token:  ${{ secrets.G_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.3"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with: 
          version: 9.1.1
      - name: Install packages
        run: pnpm i
      - name: Publish package
        run: npx jsr publish